#ifndef KEYBOARD_H
#define KEYBOARD_H

#define KEYBOARD_BUFFER_SIZE 256

#define KEYBOARD_KEYCODE_CAPSLOCK 0x3A
#define KEYBOARD_MASK_SPECIAL 0x80
#define KEYBOARD_KEYCODE_LSHIFT_PRESS 0x2A
#define KEYBOARD_KEYCODE_RSHIFT_PRESS 0x36
#define KEYBOARD_KEYCODE_LSHIFT_RELEASE 0xAA
#define KEYBOARD_KEYCODE_RSHIFT_RELEASE 0xB6

void InitializeKeyboard();
void keyboard_handler();
char getchar();

#endif
